const sampleUsers =[
  {
    "name": "Aarav Patel",
    "email": "aarav.patel@example.com",
    "password": "Password@123",
    "role": "alumni",
    "profilePic": {url:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6RgUOsdlHbbgLzYYjswj6_ktDtJLEKiLLvsV2r3wnS-VQowH5dCH_IN42SHlGdcsmWdz9CQ&s"},
    "batch": "2018",
    "company": "InnoTech Solutions",
    "position": "Senior Software Engineer",
    "experience": "5 years",
    "skills": ["Node.js", "Express", "MongoDB", "AWS"],
    "linkedin": "https://linkedin.com/in/aarav-patel",
    "github": "https://github.com/aaravpatel",
    "verified": true,
    "course": "",
    "year": "",
    "bio": "Backend engineer focused on scalable APIs.",
    "createdAt": "2024-03-01T09:12:00.000Z"
  },
  {
    "name": "Meera Singh",
    "email": "meera.singh@example.com",
    "password": "Password@123",
    "role": "alumni",
    "profilePic": {url:"https://media.istockphoto.com/id/1450788989/photo/portrait-of-happy-african-businesswoman-holding-digital-tablet-in-the-office.jpg?s=612x612&w=0&k=20&c=aalIPdiN9iTx45CkGrGMlGn-LVyICKzNvgoARsyAArg="},
    "batch": "2016",
    "company": "DataVista",
    "position": "Data Scientist",
    "experience": "6 years",
    "skills": ["Python", "Pandas", "TensorFlow", "SQL"],
    "linkedin": "https://linkedin.com/in/meera-singh",
    "github": "https://github.com/meera-s",
    "verified": true,
    "course": "",
    "year": "",
    "bio": "I build ML models for business insights.",
    "createdAt": "2024-01-20T14:25:00.000Z"
  },
  {
    "name": "Rohan Verma",
    "email": "rohan.verma@example.com",
    "password": "Password@123",
    "role": "student",
    "profilePic": {url:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSj7VsGZaoUMvDsGEm8m8k7zBospEFmoCceRNW6Jeo5vVglcJ7RBKkRqfaPntgSb9V9dKw59A&s"},
    "batch": "",
    "company": "",
    "position": "",
    "experience": "",
    "skills": ["C++", "Algorithms"],
    "linkedin": "",
    "github": "https://github.com/rohanv98",
    "verified": false,
    "course": "B.Tech Computer Science",
    "year": "3rd Year",
    "bio": "Competitive programmer passionate about system design.",
    "createdAt": "2024-08-30T10:05:00.000Z"
  },
  {
    "name": "Anjali Rao",
    "email": "anjali.rao@example.com",
    "password": "Password@123",
    "role": "alumni",
    //"profilePic": "https://example.com/avatars/anjali.jpg",
    "batch": "2014",
    "company": "GreenGrid",
    "position": "Product Manager",
    "experience": "8 years",
    "skills": ["Product Management", "UX", "Roadmapping"],
    "linkedin": "https://linkedin.com/in/anjali-rao",
    "github": "",
    "verified": true,
    "course": "",
    "year": "",
    "bio": "Ex-engineer turned PM; building sustainable tech products.",
    "createdAt": "2023-11-05T08:40:00.000Z"
  },
  {
    "name": "Vikram Iyer",
    "email": "vikram.iyer@example.com",
    "password": "Password@123",
    "role": "student",
    "profilePic": {url:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSj7VsGZaoUMvDsGEm8m8k7zBospEFmoCceRNW6Jeo5vVglcJ7RBKkRqfaPntgSb9V9dKw59A&s"},
    "batch": "",
    "company": "",
    "position": "",
    "experience": "",
    "skills": ["React", "JavaScript"],
    "linkedin": "",
    "github": "https://github.com/vikramiyer",
    "verified": false,
    "course": "B.Tech Information Technology",
    "year": "2nd Year",
    "bio": "Frontend developer building interactive UIs.",
    "createdAt": "2024-09-10T16:00:00.000Z"
  },
  {
    "name": "Priya Nair",
    "email": "priya.nair@example.com",
    "password": "Password@123",
    "role": "alumni",
    "profilePic": {url:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQQOG-VRze30HxpAnO0YJGKN7NRIBz9bdu5VA&s"},
    "batch": "2020",
    "company": "FinEdge",
    "position": "QA Engineer",
    "experience": "3 years",
    "skills": ["Selenium", "Java", "Postman"],
    "linkedin": "https://linkedin.com/in/priya-nair",
    "github": "https://github.com/priyanair",
    "verified": false,
    "course": "",
    "year": "",
    "bio": "Quality assurance specialist focused on automation.",
    "createdAt": "2024-02-11T11:30:00.000Z"
  },
  {
    "name": "Karan Malhotra",
    "email": "karan.malhotra@example.com",
    "password": "Password@123",
    "role": "admin",
    //"profilePic": "",
    "batch": "",
    "company": "",
    "position": "Platform Admin",
    "experience": "10 years",
    "skills": ["Administration", "Security"],
    "linkedin": "",
    "github": "",
    "verified": true,
    "course": "",
    "year": "",
    "bio": "Admin — manages platform and approvals.",
    "createdAt": "2023-06-18T07:50:00.000Z"
  },
  {
    "name": "Fatima Khan",
    "email": "fatima.khan@example.com",
    "password": "Password@123",
    "role": "alumni",
    "profilePic": {url:"https://media.istockphoto.com/id/1368076322/photo/portrait-of-a-confident-businesswoman-in-an-office.jpg?s=612x612&w=0&k=20&c=C55I_Kag1Ha7azdIjfsYPZQZXeztho4agsTHxNpYQNw= "},
    "batch": "2017",
    "company": "CloudNine",
    "position": "DevOps Engineer",
    "experience": "6 years",
    "skills": ["Docker", "Kubernetes", "Terraform", "AWS"],
    "linkedin": "https://linkedin.com/in/fatima-khan",
    "github": "https://github.com/fatimak",
    "verified": true,
    "course": "",
    "year": "",
    "bio": "I automate infra and CI/CD pipelines.",
    "createdAt": "2024-04-02T12:10:00.000Z"
  },
  {
    "name": "Sandeep Sharma",
    "email": "sandeep.sharma@example.com",
    "password": "Password@123",
    "role": "student",
    //"profilePic": "",
    "batch": "",
    "company": "",
    "position": "",
    "experience": "",
    "skills": ["Python", "Django"],
    "linkedin": "",
    "github": "https://github.com/sandeepsh",
    "verified": false,
    "course": "MCA",
    "year": "1st Year",
    "bio": "Aspiring backend dev learning Django and APIs.",
    "createdAt": "2024-09-01T09:00:00.000Z"
  },
  {
    "name": "Nisha Gupta",
    "email": "nisha.gupta@example.com",
    "password": "Password@123",
    "role": "alumni",
    "profilePic": {url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUqL0rOF54vjDV8ACciqsCPmamAy4_8NFHVg&s"},
    "batch": "2015",
    "company": "HealthPlus",
    "position": "QA Lead",
    "experience": "7 years",
    "skills": ["Manual Testing", "Automation", "Test Planning"],
    "linkedin": "https://linkedin.com/in/nisha-gupta",
    "github": "",
    "verified": true,
    "course": "",
    "year": "",
    "bio": "Leading QA teams in health-tech.",
    "createdAt": "2023-12-12T13:45:00.000Z"
  },
  {
    "name": "Aditya Joshi",
    "email": "aditya.joshi@example.com",
    "password": "Password@123",
    "role": "student",
    "profilePic": {url:"https://img.freepik.com/premium-photo/man-with-arms-crossed-standing-front-window-dynamic-tech-startup-founder-incorporating-islamic-principles-into-his-innovative-business-model_538213-71092.jpg?semt=ais_hybrid&w=740&q=80"},
    "batch": "",
    "company": "",
    "position": "",
    "experience": "",
    "skills": ["Java", "Spring Boot"],
    "linkedin": "",
    "github": "https://github.com/adityaj",
    "verified": false,
    "course": "B.Tech Computer Science",
    "year": "4th Year",
    "bio": "Building microservices and learning cloud patterns.",
    "createdAt": "2024-05-16T18:20:00.000Z"
  },
  {
    "name": "Sheetal Desai",
    "email": "sheetal.desai@example.com",
    "password": "Password@123",
    "role": "alumni",
    "profilePic": {url:"https://assets.entrepreneur.com/slideshow/1601675234-NicoleGibbons-ClarePaint-CEO-2.jpg?auto=webp&quality=95&width=675"},
    "batch": "2019",
    "company": "EduWave",
    "position": "Frontend Engineer",
    "experience": "4 years",
    "skills": ["HTML", "CSS", "React", "TypeScript"],
    "linkedin": "https://linkedin.com/in/sheetal-desai",
    "github": "https://github.com/sheetaldesai",
    "verified": false,
    "course": "",
    "year": "",
    "bio": "Design-focused frontend engineer.",
    "createdAt": "2024-06-08T10:55:00.000Z"
  },
  {
    "name": "Mohit Gupta",
    "email": "mohit.gupta@example.com",
    "password": "Password@123",
    "role": "alumni",
    "profilePic": {url:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQZbIfkzUmWtAo3-g5DALGWfPSa3CqiJBQp6w&s"},
    "batch": "2013",
    "company": "SecureNet",
    "position": "Security Analyst",
    "experience": "11 years",
    "skills": ["Cybersecurity", "Penetration Testing", "SIEM"],
    "linkedin": "https://linkedin.com/in/mohit-gupta",
    "github": "",
    "verified": true,
    "course": "",
    "year": "",
    "bio": "Security professional with enterprise experience.",
    "createdAt": "2022-10-03T06:30:00.000Z"
  },
  {
    "name": "Ishita Banerjee",
    "email": "ishita.banerjee@example.com",
    "password": "Password@123",
    "role": "student",
    "profilePic": {url:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTx0J83qAqUYtvdnRpDD7fjKRGkY8B9gA7X_A&s"},
    "batch": "",
    "company": "",
    "position": "",
    "experience": "",
    "skills": ["UI Design", "Figma"],
    "linkedin": "",
    "github": "",
    "verified": false,
    "course": "B.Des",
    "year": "2nd Year",
    "bio": "Design student focusing on user experiences.",
    "createdAt": "2024-07-22T15:40:00.000Z"
  },
  {
    "name": "Arjun Mehta",
    "email": "arjun.mehta@example.com",
    "password": "Password@123",
    "role": "alumni",
    "profilePic": {url:"https://cdn.techinasia.com/wp-content/uploads/2021/07/1626143867_2f0f43c98db1689a720bbab64152fc03_v1626143866_xlarge.webp"},
    "batch": "2021",
    "company": "NeoRetail",
    "position": "Associate Engineer",
    "experience": "2 years",
    "skills": ["Node.js", "React", "Postgres"],
    "linkedin": "https://linkedin.com/in/arjun-mehta",
    "github": "https://github.com/arjunmehta",
    "verified": false,
    "course": "",
    "year": "",
    "bio": "Building retail SaaS features.",
    "createdAt": "2024-02-28T09:00:00.000Z"
  },
  {
    "name": "Ritu Mallick",
    "email": "ritu.mallick@example.com",
    "password": "Password@123",
    "role": "student",
    "profilePic": {url:"https://images.pexels.com/photos/1462630/pexels-photo-1462630.jpeg?cs=srgb&dl=pexels-anastasiya-gepp-654466-1462630.jpg&fm=jpg"},
    "batch": "",
    "company": "",
    "position": "",
    "experience": "",
    "skills": ["Machine Learning", "Python"],
    "linkedin": "",
    "github": "https://github.com/ritumallick",
    "verified": false,
    "course": "M.Sc Data Science",
    "year": "2nd Year",
    "bio": "Exploring NLP and computer vision.",
    "createdAt": "2024-03-18T20:15:00.000Z"
  },
  {
    "name": "Devansh Kapoor",
    "email": "devansh.kapoor@example.com",
    "password": "Password@123",
    "role": "admin",
    //"profilePic": "",
    "batch": "",
    "company": "",
    "position": "Super Admin",
    "experience": "12 years",
    "skills": ["DevOps", "Admin"],
    "linkedin": "",
    "github": "",
    "verified": true,
    "course": "",
    "year": "",
    "bio": "Platform owner and administrator.",
    "createdAt": "2021-01-02T07:00:00.000Z"
  },
  {
    "name": "Lavanya Reddy",
    "email": "lavanya.reddy@example.com",
    "password": "Password@123",
    "role": "alumni",
    "profilePic": {url:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRWjhT4GQl2-iRzVlY3_5v9GIzqRKZ7KhTrQA&s"},
    "batch": "2012",
    "company": "BioHealth",
    "position": "Research Engineer",
    "experience": "13 years",
    "skills": ["MATLAB", "Data Analysis", "R"],
    "linkedin": "https://linkedin.com/in/lavanya-reddy",
    "github": "",
    "verified": true,
    "course": "",
    "year": "",
    "bio": "Researcher in biomedical signal processing.",
    "createdAt": "2020-05-30T11:11:00.000Z"
  },
  {
    "name": "Sameer Khan",
    "email": "sameer.khan@example.com",
    "password": "Password@123",
    "role": "student",
    //"profilePic": "",
    "batch": "",
    "company": "",
    "position": "",
    "experience": "",
    "skills": ["Go", "Microservices"],
    "linkedin": "",
    "github": "https://github.com/sameerk",
    "verified": false,
    "course": "B.Tech Computer Science",
    "year": "4th Year",
    "bio": "Interested in scalable backend systems.",
    "createdAt": "2024-04-25T19:30:00.000Z"
  },
  {
    "name": "Zoya Ahmed",
    "email": "zoya.ahmed@example.com",
    "password": "Password@123",
    "role": "alumni",
    //"profilePic": "https://example.com/avatars/zoya.jpg",
    "batch": "2010",
    "company": "MediaLoop",
    "position": "Senior Designer",
    "experience": "14 years",
    "skills": ["Illustrator", "Photoshop", "Branding"],
    "linkedin": "https://linkedin.com/in/zoya-ahmed",
    "github": "",
    "verified": true,
    "course": "",
    "year": "",
    "bio": "Designer focused on brand identity and UX.",
    "createdAt": "2019-09-09T09:09:00.000Z"
  }
]

module.exports = { data: sampleUsers };